# Generated by Django 3.2.9 on 2021-12-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20211220_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorias',
            name='descripcion',
            field=models.CharField(default='Descripción de la categoría', max_length=200, verbose_name='Descripción de la categoría'),
        ),
    ]
