# Generated by Django 3.2.9 on 2021-12-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_categorias_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Imagen'),
        ),
    ]
