# Generated by Django 3.2.9 on 2021-12-20 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='p_id',
            new_name='id',
        ),
    ]
