# Generated by Django 3.2.9 on 2021-12-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='tipo',
            field=models.BooleanField(default=False, verbose_name='Administrador'),
        ),
    ]
