# Generated by Django 3.2.9 on 2021-12-20 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_autor_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='web',
            field=models.URLField(verbose_name='Red social/website'),
        ),
    ]
