# Generated by Django 3.2.9 on 2021-12-20 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_autor_web'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='web',
        ),
    ]
