# Generated by Django 3.2.9 on 2021-12-20 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_autor_web'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='password',
            field=models.CharField(default='1234', max_length=12, verbose_name='password'),
        ),
    ]
