# Generated by Django 3.2.9 on 2021-12-20 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_autor_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='password',
        ),
    ]
